### ISSUE TITLE
temp.ico could not be found.

### ISSUE THREAD

**Issue by EmaSuriano** [Haruki1707/ShortCutes#3] opened 2022-10-24 12:08 UTC
I cannot create any shortcut for the emulator yuzu. I filled all the information asked in the form, and when I hit submit I receive this error.

![image](https://user-images.githubusercontent.com/3399429/197521997-5cfcce76-f4a6-47e1-b144-ad1acad3cefc.png)

Any idea how to fix it?

Version: 1.4.3

**Comment by EmaSuriano** [comment] 2022-10-24 12:12
If I check the files inside that folder, I do have all the files required.

![image](https://user-images.githubusercontent.com/3399429/197522698-88f2a0ae-83eb-4336-bf8d-e9eff3889c6e.png)

**Comment by Haruki1707** [comment] 2022-10-24 18:27
I will check it and try to find a solution for it, I think I already know which is the problem. After fixing it I will upload a update

**Comment by Haruki1707** [comment] 2022-10-27 01:51
I already found the error, C# sometimes does not escape spaces correctly, and cause your pc user name has an space is the bug happening, I will fix today and upload and update tomorrow

**Comment by Haruki1707** [comment] 2022-10-27 02:51
The problem is now fixed and you can download latest version here [https://github.com/Haruki1707/ShortCutes/releases/latest/download/ShortCutes.exe](https://github.com/Haruki1707/ShortCutes/releases/latest/download/ShortCutes.exe)

**Closed by Haruki1707** 2022-10-27 02:51 UTC
