### ISSUE TITLE
Value does not fall within the expected range.

### ISSUE THREAD

**Issue by Cocytus45** [Haruki1707/ShortCutes#9] opened 2023-06-01 00:39 UTC
### Error:
Received this error when trying to create a shortcut for ボクらの消しゴム落とし3 世界編. The shortcut is generated correctly and the game launches perfectly fine but the application hangs and must be restarted after creating the shortcut.

![Screenshot 2023-05-31 201153](https://github.com/Haruki1707/ShortCutes/assets/134197768/2e7cb746-d327-4539-b05d-e597d8ea4a92)
**Repeatability**: ✔️

### Notes:
I believe the error is related to the shortcut name, since creating the shortcut in English appears to work perfectly fine.

### Scenario Details:
Shortcut Name: ボクらの消しゴム落とし3 世界編
Image Link: https://images.eshop-prices.com/games/11550/480w.jpeg
Shortcut Design: square
Desktop Shortcut: ✔️
Force launcher to close: ✖️

Emulator: Yuzu
App version: Shortcutes v1.5.2
OS: Windows 11 22H2 Build 22621.1702

**Comment by Haruki1707** [comment] 2023-06-01 12:55
Yeah, must be the foreign characters, I will try to check if there is a way to add support for them

**Comment by Cocytus45** [comment] 2023-06-02 03:20
Sounds good, though since the shortcut is still technically generated and works fine I wouldn't be too concerned.

**Comment by Haruki1707** [comment] 2023-06-02 05:17
![image](https://github.com/Haruki1707/ShortCutes/assets/72423267/e2c0834f-9c3f-4b4c-be92-1a743e543e6a)

I have solved the problem! It was caused by an outdated system library that didn't support UNICODE characters. I will include the fix for this issue in the next update, along with a fix for this other issue #8.

**Comment by Cocytus45** [comment] 2023-06-02 07:59
Awesome nice job, thanks!

**Closed** 2023-06-02 07:59 UTC
